name: React workflow
on:
  pull_request:
  push:
    branches:
      - develop
      - master
  create:
    tags:
      - v*

jobs:
  lint:
    name: Run the linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: npm ci
      - run: make lint
  build:
    name: Deploy the app
    needs: [lint]
    runs-on: ubuntu-latest
    env:
      COMMIT: ${{ github.sha }}
      VERSION: ${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arthureichelberger
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.1
      - run: make deploy
